/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.reflex.impl;

import org.eclipse.emf.ecore.EClass;

import ru.iaie.reflex.diagram.reflex.BitXorExpression;
import ru.iaie.reflex.diagram.reflex.ReflexPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bit Xor Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BitXorExpressionImpl extends BitOrExpressionImpl implements BitXorExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BitXorExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReflexPackage.Literals.BIT_XOR_EXPRESSION;
  }

} //BitXorExpressionImpl
