/*
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ru.iaie.reflex.diagram.ui.internal.DiagramActivator;

public class ReflexUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DiagramActivator.getInstance().getInjector("ru.iaie.reflex.diagram.Reflex");
	}

}
