/*
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import ru.iaie.reflex.diagram.ui.internal.DiagramActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReflexExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DiagramActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DiagramActivator activator = DiagramActivator.getInstance();
		return activator != null ? activator.getInjector(DiagramActivator.RU_IAIE_REFLEX_DIAGRAM_REFLEX) : null;
	}

}
