/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.reflex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case Stat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.diagram.reflex.CaseStat#getOption <em>Option</em>}</li>
 *   <li>{@link ru.iaie.reflex.diagram.reflex.CaseStat#getBody <em>Body</em>}</li>
 *   <li>{@link ru.iaie.reflex.diagram.reflex.CaseStat#isHasBreak <em>Has Break</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getCaseStat()
 * @model
 * @generated
 */
public interface CaseStat extends EObject
{
  /**
   * Returns the value of the '<em><b>Option</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Option</em>' attribute.
   * @see #setOption(String)
   * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getCaseStat_Option()
   * @model
   * @generated
   */
  String getOption();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.diagram.reflex.CaseStat#getOption <em>Option</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Option</em>' attribute.
   * @see #getOption()
   * @generated
   */
  void setOption(String value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Statement)
   * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getCaseStat_Body()
   * @model containment="true"
   * @generated
   */
  Statement getBody();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.diagram.reflex.CaseStat#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Statement value);

  /**
   * Returns the value of the '<em><b>Has Break</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Break</em>' attribute.
   * @see #setHasBreak(boolean)
   * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getCaseStat_HasBreak()
   * @model
   * @generated
   */
  boolean isHasBreak();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.diagram.reflex.CaseStat#isHasBreak <em>Has Break</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Break</em>' attribute.
   * @see #isHasBreak()
   * @generated
   */
  void setHasBreak(boolean value);

} // CaseStat
