/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.reflex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compound Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getCompoundStatement()
 * @model
 * @generated
 */
public interface CompoundStatement extends Statement
{
} // CompoundStatement
