/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.reflex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.diagram.reflex.ProgramVariable#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getProgramVariable()
 * @model
 * @generated
 */
public interface ProgramVariable extends DeclaredVariable
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(ReflexType)
   * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getProgramVariable_Type()
   * @model containment="true"
   * @generated
   */
  ReflexType getType();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.diagram.reflex.ProgramVariable#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(ReflexType value);

} // ProgramVariable
