/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.reflex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.diagram.reflex.Statement#isLoop <em>Loop</em>}</li>
 *   <li>{@link ru.iaie.reflex.diagram.reflex.Statement#isRestart <em>Restart</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Loop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop</em>' attribute.
   * @see #setLoop(boolean)
   * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getStatement_Loop()
   * @model
   * @generated
   */
  boolean isLoop();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.diagram.reflex.Statement#isLoop <em>Loop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loop</em>' attribute.
   * @see #isLoop()
   * @generated
   */
  void setLoop(boolean value);

  /**
   * Returns the value of the '<em><b>Restart</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Restart</em>' attribute.
   * @see #setRestart(boolean)
   * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getStatement_Restart()
   * @model
   * @generated
   */
  boolean isRestart();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.diagram.reflex.Statement#isRestart <em>Restart</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Restart</em>' attribute.
   * @see #isRestart()
   * @generated
   */
  void setRestart(boolean value);

} // Statement
