/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.reflex;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Timeout Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.diagram.reflex.TimeoutFunction#getTime <em>Time</em>}</li>
 *   <li>{@link ru.iaie.reflex.diagram.reflex.TimeoutFunction#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getTimeoutFunction()
 * @model
 * @generated
 */
public interface TimeoutFunction extends EObject
{
  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(Time)
   * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getTimeoutFunction_Time()
   * @model containment="true"
   * @generated
   */
  Time getTime();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.diagram.reflex.TimeoutFunction#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(Time value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link ru.iaie.reflex.diagram.reflex.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getTimeoutFunction_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // TimeoutFunction
