/**
 * generated by Xtext 2.20.0
 */
package ru.iaie.reflex.diagram.reflex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ru.iaie.reflex.diagram.reflex.ReflexPackage#getVariable()
 * @model
 * @generated
 */
public interface Variable extends EObject
{
} // Variable
